### ISSUE TITLE
Node <12 compatibility is broken because of String.concat

### ISSUE THREAD

**Issue by aesedepece** [witnet/truffle-box#5]

**Comment by Tommytrg** [comment]
The test in witnet/witnet-solidity-bridge#244 are broken because truffle is going to deprecate support for node@12

**Comment by Tommytrg** [comment]
Node v12 is deprecated:

![image](https://user-images.githubusercontent.com/24905681/225914651-5e5b6be2-b2ae-43cd-bb56-b60bb06e9c4c.png)
Source: https://github.com/nodejs/Release/blob/main/schedule.svg
